# Purpose: Docker Compose configuration for PODVOX backend and frontend development

services:
  backend:
    build: ./backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app            # Hot-reload for dev
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - backend 