# Purpose: Docker Compose configuration for PODVOX backend development

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount only the app directory for hot reloading
      - ./app:/app/app:delegated
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app 